language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

notifications:
  email: false

deploy:
  provider: openshift
  user: iololoiev
  password:
    secure: kiHHOXCF9ej4wMBDIua9TliTVwjf676abla2bctMO1WqWWC3YL5LKJ1dq3WXNDWEVERfQw9MrUf+65veMu0gHVW14RiDk5QygX0vghNIkb+Ij9t1OKHQfVue5a6c2/0XqxNZTBbsCDkO6MMaYTYkp8m9uhSnIt0PD+S/QOT6n19NAbDPBv8QG/QtBy/b050Uim29FQgj4/qHBVfmQCBmp61FxGhp3BKq+rttqLYByQDGFmaYetoJedoCIozAIussImNV+wBlhcea83QU05vWMUezWZqwq9a12LAQzE6vQLQIeqgn6K78ALkkJOCyb6vfoaVh9NIGuq+p7I4+zaWFFzZTDf4JhFPAVf4Y6COWV28QJ7yTMKNWrr5zQtVj3pZczLS+BYFwbxnAWaSXuRGalA9lVGTeHiCgEwqA0ytq4TCBXL2dKkyuhgi7RolASZN73OV4zFdE03NSaXk4D/A4w9JMp230h6+i/eoq1YvMMmIjvfk1F2Fx2KvCPlirt/Lv6JUkymWsB230xN8lxCWk1MDZiMjZ3jPZpMEAGhgf36ishFW+P4ROdiNMnncjbSt/tofR6c5JAIKVwbgi4aDKm13fSTwi4y/qaL/pb4dOjT/QTYFRTtYR+i1z3K6qnCooiLPOsLMh/F0WvNMEwstmQm8vvD3n3grVyt+W4QodHS0=
  domain: console.starter-ca-central-1.openshift.com
  app: echo-bot
  on:
    repo: ololoiev/bot
    master
