language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

notifications:
  email: false

deploy:
  provider: openshift
  user: iololoiev
  password: LnIkLH5732PlWQvG21672HC
  domain: console.starter-ca-central-1.openshift.com
  app: echo-bot
